### PR TITLE
fixed cv2.resize error and type error of labels, the modified files are in datasets_v2.py and train_base_v2.py.

### PR DESCRIPTION
**Pull request by IrumaMegumi**

### CODE REVIEW

**Review by SunnyHaze — CHANGES_REQUESTED** [review]
Thanks for your time and contribution. However, I think some problems should be addressed before merging.
1. A PR with extra “v2” python files does not seem very elegant since it introduces redundant codes.
2. Some changes on `train_base_v2.py` seem unrelated to the specified issue #11.

Therefore, I kindly suggest that you could point out which line or function causes this `cv2.resize()` issue, and only make minimum modifications in an `in place` manner.

Thanks again for your pull request, if need further discussion you could contact me by email then we can discuss it through QQ or WeChat.

**Comment by IrumaMegumi** [comment]
In your original /datasets/dataset.py file, I added a line. Without it will cause a cv2.resize error.
image

**Comment by IrumaMegumi** [comment]
Position is near line 493.

**Comment by SunnyHaze** [comment]
Thanks for you clarify of the bugging line and fixing this bug, and sorry for our negligence of this bug.
Besides, I deleted the extra train_base_v2.py file manually to keep the main branch clean. If you want to keep it in your own repository, you can still find it in previous commits and copy it offline.

**Review by SunnyHaze — APPROVED** [review]

**Comment by IrumaMegumi** [comment]
OK,thanks. If you like, you can cantact me at QQ:2286453531

**Pull request merged**
